### ISSUE TITLE
Only add 'ver' query arg if script/style ver property === false

### ISSUE THREAD

**Issue by dotsam** [wearerequired/h2push#2]
First off, thanks for the plugin. Does exactly what I want in a nice lightweight manner.

I have found a bug however in how the plugin is appending `'ver'` query args to URLs. As per the WordPress docs (https://developer.wordpress.org/reference/functions/wp_enqueue_style/), the WordPress version is only added if $ver is set to `false` (also the default). If $ver is set to `null` instead, no version string is added.

Your [check](https://github.com/wearerequired/h2push/blob/master/h2push.php#L102) for `!empty()` catches both cases the same. There needs to be another outcome where no query argument is added when `$ver === null`.

**Comment by ocean90** [comment]
Hi @dotsam, sorry for late response!

Thanks for the hint, wasn't aware of the `null` feature. I'll update the plugin to not add the version in this case.
